/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class AdvSecEnablementUpdate {
  @JsonProperty("newDependabotStatus")
  private Boolean newDependabotStatus = null;

  @JsonProperty("newStatus")
  private Boolean newStatus = null;

  @JsonProperty("projectId")
  private UUID projectId = null;

  @JsonProperty("repositoryId")
  private UUID repositoryId = null;

  public AdvSecEnablementUpdate newDependabotStatus(Boolean newDependabotStatus) {
    this.newDependabotStatus = newDependabotStatus;
    return this;
  }

   /**
   * New Dependabot status.
   * @return newDependabotStatus
  **/
  @ApiModelProperty(value = "New Dependabot status.")
  public Boolean isNewDependabotStatus() {
    return newDependabotStatus;
  }

  public void setNewDependabotStatus(Boolean newDependabotStatus) {
    this.newDependabotStatus = newDependabotStatus;
  }

  public AdvSecEnablementUpdate newStatus(Boolean newStatus) {
    this.newStatus = newStatus;
    return this;
  }

   /**
   * New status
   * @return newStatus
  **/
  @ApiModelProperty(value = "New status")
  public Boolean isNewStatus() {
    return newStatus;
  }

  public void setNewStatus(Boolean newStatus) {
    this.newStatus = newStatus;
  }

  public AdvSecEnablementUpdate projectId(UUID projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * ProjectId
   * @return projectId
  **/
  @ApiModelProperty(value = "ProjectId")
  public UUID getProjectId() {
    return projectId;
  }

  public void setProjectId(UUID projectId) {
    this.projectId = projectId;
  }

  public AdvSecEnablementUpdate repositoryId(UUID repositoryId) {
    this.repositoryId = repositoryId;
    return this;
  }

   /**
   * RepositoryId Actual RepositoryId to Modify or Magic Repository Id \&quot;FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF\&quot; for ALL Repositories for that project
   * @return repositoryId
  **/
  @ApiModelProperty(value = "RepositoryId Actual RepositoryId to Modify or Magic Repository Id \"FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF\" for ALL Repositories for that project")
  public UUID getRepositoryId() {
    return repositoryId;
  }

  public void setRepositoryId(UUID repositoryId) {
    this.repositoryId = repositoryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvSecEnablementUpdate advSecEnablementUpdate = (AdvSecEnablementUpdate) o;
    return Objects.equals(this.newDependabotStatus, advSecEnablementUpdate.newDependabotStatus) &&
        Objects.equals(this.newStatus, advSecEnablementUpdate.newStatus) &&
        Objects.equals(this.projectId, advSecEnablementUpdate.projectId) &&
        Objects.equals(this.repositoryId, advSecEnablementUpdate.repositoryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newDependabotStatus, newStatus, projectId, repositoryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvSecEnablementUpdate {\n");
    
    sb.append("    newDependabotStatus: ").append(toIndentedString(newDependabotStatus)).append("\n");
    sb.append("    newStatus: ").append(toIndentedString(newStatus)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    repositoryId: ").append(toIndentedString(repositoryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

