/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;
import therealflamingo.ado.models.IdentityRef;
import therealflamingo.ado.models.PropertiesCollection;
import therealflamingo.ado.models.ReferenceLinks;

/**
 * Meta data for a file attached to an artifact.
 */
@ApiModel(description = "Meta data for a file attached to an artifact.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class Attachment {
  @JsonProperty("_links")
  private ReferenceLinks links = null;

  @JsonProperty("author")
  private IdentityRef author = null;

  @JsonProperty("contentHash")
  private String contentHash = null;

  @JsonProperty("createdDate")
  private OffsetDateTime createdDate = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("properties")
  private PropertiesCollection properties = null;

  @JsonProperty("url")
  private String url = null;

  public Attachment links(ReferenceLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Links to other related objects.
   * @return links
  **/
  @ApiModelProperty(value = "Links to other related objects.")
  public ReferenceLinks getLinks() {
    return links;
  }

  public void setLinks(ReferenceLinks links) {
    this.links = links;
  }

  public Attachment author(IdentityRef author) {
    this.author = author;
    return this;
  }

   /**
   * The person that uploaded this attachment.
   * @return author
  **/
  @ApiModelProperty(value = "The person that uploaded this attachment.")
  public IdentityRef getAuthor() {
    return author;
  }

  public void setAuthor(IdentityRef author) {
    this.author = author;
  }

  public Attachment contentHash(String contentHash) {
    this.contentHash = contentHash;
    return this;
  }

   /**
   * Content hash of on-disk representation of file content. Its calculated by the server by using SHA1 hash function.
   * @return contentHash
  **/
  @ApiModelProperty(value = "Content hash of on-disk representation of file content. Its calculated by the server by using SHA1 hash function.")
  public String getContentHash() {
    return contentHash;
  }

  public void setContentHash(String contentHash) {
    this.contentHash = contentHash;
  }

  public Attachment createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The time the attachment was uploaded.
   * @return createdDate
  **/
  @ApiModelProperty(value = "The time the attachment was uploaded.")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

  public Attachment description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the attachment.
   * @return description
  **/
  @ApiModelProperty(value = "The description of the attachment.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Attachment displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the attachment. Can&#39;t be null or empty.
   * @return displayName
  **/
  @ApiModelProperty(value = "The display name of the attachment. Can't be null or empty.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public Attachment id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the attachment.
   * @return id
  **/
  @ApiModelProperty(value = "Id of the attachment.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Attachment properties(PropertiesCollection properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Extended properties.
   * @return properties
  **/
  @ApiModelProperty(value = "Extended properties.")
  public PropertiesCollection getProperties() {
    return properties;
  }

  public void setProperties(PropertiesCollection properties) {
    this.properties = properties;
  }

  public Attachment url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The url to download the content of the attachment.
   * @return url
  **/
  @ApiModelProperty(value = "The url to download the content of the attachment.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attachment attachment = (Attachment) o;
    return Objects.equals(this.links, attachment.links) &&
        Objects.equals(this.author, attachment.author) &&
        Objects.equals(this.contentHash, attachment.contentHash) &&
        Objects.equals(this.createdDate, attachment.createdDate) &&
        Objects.equals(this.description, attachment.description) &&
        Objects.equals(this.displayName, attachment.displayName) &&
        Objects.equals(this.id, attachment.id) &&
        Objects.equals(this.properties, attachment.properties) &&
        Objects.equals(this.url, attachment.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, author, contentHash, createdDate, description, displayName, id, properties, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attachment {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    contentHash: ").append(toIndentedString(contentHash)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

