/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import therealflamingo.ado.models.BillableCommitter;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class BillableCommitterDetail extends BillableCommitter {
  @JsonProperty("repoId")
  private UUID repoId = null;

  @JsonProperty("vsid")
  private UUID vsid = null;

  @JsonProperty("commitId")
  private String commitId = null;

  @JsonProperty("committerEmail")
  private String committerEmail = null;

  @JsonProperty("commitTime")
  private OffsetDateTime commitTime = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("mailNickName")
  private String mailNickName = null;

  @JsonProperty("projectId")
  private UUID projectId = null;

  @JsonProperty("projectName")
  private String projectName = null;

  @JsonProperty("pushedTime")
  private OffsetDateTime pushedTime = null;

  @JsonProperty("pusherId")
  private UUID pusherId = null;

  @JsonProperty("pushId")
  private Integer pushId = null;

  @JsonProperty("repoName")
  private String repoName = null;

  @JsonProperty("samAccountName")
  private String samAccountName = null;

  public BillableCommitterDetail repoId(UUID repoId) {
    this.repoId = repoId;
    return this;
  }

   /**
   * RepositoryId commit was pushed to.
   * @return repoId
  **/
  @ApiModelProperty(value = "RepositoryId commit was pushed to.")
  public UUID getRepoId() {
    return repoId;
  }

  public void setRepoId(UUID repoId) {
    this.repoId = repoId;
  }

  public BillableCommitterDetail vsid(UUID vsid) {
    this.vsid = vsid;
    return this;
  }

   /**
   * Visual Studio ID /Team Foundation ID
   * @return vsid
  **/
  @ApiModelProperty(value = "Visual Studio ID /Team Foundation ID")
  public UUID getVsid() {
    return vsid;
  }

  public void setVsid(UUID vsid) {
    this.vsid = vsid;
  }

  public BillableCommitterDetail commitId(String commitId) {
    this.commitId = commitId;
    return this;
  }

   /**
   * ID (SHA-1) of the commit.
   * @return commitId
  **/
  @ApiModelProperty(value = "ID (SHA-1) of the commit.")
  public String getCommitId() {
    return commitId;
  }

  public void setCommitId(String commitId) {
    this.commitId = commitId;
  }

  public BillableCommitterDetail committerEmail(String committerEmail) {
    this.committerEmail = committerEmail;
    return this;
  }

   /**
   * Committer email address after parsing.
   * @return committerEmail
  **/
  @ApiModelProperty(value = "Committer email address after parsing.")
  public String getCommitterEmail() {
    return committerEmail;
  }

  public void setCommitterEmail(String committerEmail) {
    this.committerEmail = committerEmail;
  }

  public BillableCommitterDetail commitTime(OffsetDateTime commitTime) {
    this.commitTime = commitTime;
    return this;
  }

   /**
   * Time reported by the commit.
   * @return commitTime
  **/
  @ApiModelProperty(value = "Time reported by the commit.")
  public OffsetDateTime getCommitTime() {
    return commitTime;
  }

  public void setCommitTime(OffsetDateTime commitTime) {
    this.commitTime = commitTime;
  }

  public BillableCommitterDetail displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * DisplayName of the Pusher.
   * @return displayName
  **/
  @ApiModelProperty(value = "DisplayName of the Pusher.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public BillableCommitterDetail mailNickName(String mailNickName) {
    this.mailNickName = mailNickName;
    return this;
  }

   /**
   * MailNickName of the Pusher.
   * @return mailNickName
  **/
  @ApiModelProperty(value = "MailNickName of the Pusher.")
  public String getMailNickName() {
    return mailNickName;
  }

  public void setMailNickName(String mailNickName) {
    this.mailNickName = mailNickName;
  }

  public BillableCommitterDetail projectId(UUID projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Project Id commit was pushed to.
   * @return projectId
  **/
  @ApiModelProperty(value = "Project Id commit was pushed to.")
  public UUID getProjectId() {
    return projectId;
  }

  public void setProjectId(UUID projectId) {
    this.projectId = projectId;
  }

  public BillableCommitterDetail projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Project name commit was pushed to.
   * @return projectName
  **/
  @ApiModelProperty(value = "Project name commit was pushed to.")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public BillableCommitterDetail pushedTime(OffsetDateTime pushedTime) {
    this.pushedTime = pushedTime;
    return this;
  }

   /**
   * Time of the push that contained the commit.
   * @return pushedTime
  **/
  @ApiModelProperty(value = "Time of the push that contained the commit.")
  public OffsetDateTime getPushedTime() {
    return pushedTime;
  }

  public void setPushedTime(OffsetDateTime pushedTime) {
    this.pushedTime = pushedTime;
  }

  public BillableCommitterDetail pusherId(UUID pusherId) {
    this.pusherId = pusherId;
    return this;
  }

   /**
   * Pusher Id for the push.
   * @return pusherId
  **/
  @ApiModelProperty(value = "Pusher Id for the push.")
  public UUID getPusherId() {
    return pusherId;
  }

  public void setPusherId(UUID pusherId) {
    this.pusherId = pusherId;
  }

  public BillableCommitterDetail pushId(Integer pushId) {
    this.pushId = pushId;
    return this;
  }

   /**
   * Push Id that contained the commit.
   * @return pushId
  **/
  @ApiModelProperty(value = "Push Id that contained the commit.")
  public Integer getPushId() {
    return pushId;
  }

  public void setPushId(Integer pushId) {
    this.pushId = pushId;
  }

  public BillableCommitterDetail repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }

   /**
   * Repository name commit was pushed to.
   * @return repoName
  **/
  @ApiModelProperty(value = "Repository name commit was pushed to.")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public BillableCommitterDetail samAccountName(String samAccountName) {
    this.samAccountName = samAccountName;
    return this;
  }

   /**
   * SamAccountName of the Pusher.
   * @return samAccountName
  **/
  @ApiModelProperty(value = "SamAccountName of the Pusher.")
  public String getSamAccountName() {
    return samAccountName;
  }

  public void setSamAccountName(String samAccountName) {
    this.samAccountName = samAccountName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillableCommitterDetail billableCommitterDetail = (BillableCommitterDetail) o;
    return Objects.equals(this.repoId, billableCommitterDetail.repoId) &&
        Objects.equals(this.vsid, billableCommitterDetail.vsid) &&
        Objects.equals(this.commitId, billableCommitterDetail.commitId) &&
        Objects.equals(this.committerEmail, billableCommitterDetail.committerEmail) &&
        Objects.equals(this.commitTime, billableCommitterDetail.commitTime) &&
        Objects.equals(this.displayName, billableCommitterDetail.displayName) &&
        Objects.equals(this.mailNickName, billableCommitterDetail.mailNickName) &&
        Objects.equals(this.projectId, billableCommitterDetail.projectId) &&
        Objects.equals(this.projectName, billableCommitterDetail.projectName) &&
        Objects.equals(this.pushedTime, billableCommitterDetail.pushedTime) &&
        Objects.equals(this.pusherId, billableCommitterDetail.pusherId) &&
        Objects.equals(this.pushId, billableCommitterDetail.pushId) &&
        Objects.equals(this.repoName, billableCommitterDetail.repoName) &&
        Objects.equals(this.samAccountName, billableCommitterDetail.samAccountName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repoId, vsid, commitId, committerEmail, commitTime, displayName, mailNickName, projectId, projectName, pushedTime, pusherId, pushId, repoName, samAccountName, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillableCommitterDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    vsid: ").append(toIndentedString(vsid)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("    committerEmail: ").append(toIndentedString(committerEmail)).append("\n");
    sb.append("    commitTime: ").append(toIndentedString(commitTime)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    mailNickName: ").append(toIndentedString(mailNickName)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    pushedTime: ").append(toIndentedString(pushedTime)).append("\n");
    sb.append("    pusherId: ").append(toIndentedString(pusherId)).append("\n");
    sb.append("    pushId: ").append(toIndentedString(pushId)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    samAccountName: ").append(toIndentedString(samAccountName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

