/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Parameter for creating a git import request when source is Git version control
 */
@ApiModel(description = "Parameter for creating a git import request when source is Git version control")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class GitImportGitSource {
  @JsonProperty("overwrite")
  private Boolean overwrite = null;

  @JsonProperty("url")
  private String url = null;

  public GitImportGitSource overwrite(Boolean overwrite) {
    this.overwrite = overwrite;
    return this;
  }

   /**
   * Tells if this is a sync request or not
   * @return overwrite
  **/
  @ApiModelProperty(value = "Tells if this is a sync request or not")
  public Boolean isOverwrite() {
    return overwrite;
  }

  public void setOverwrite(Boolean overwrite) {
    this.overwrite = overwrite;
  }

  public GitImportGitSource url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url for the source repo
   * @return url
  **/
  @ApiModelProperty(value = "Url for the source repo")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitImportGitSource gitImportGitSource = (GitImportGitSource) o;
    return Objects.equals(this.overwrite, gitImportGitSource.overwrite) &&
        Objects.equals(this.url, gitImportGitSource.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overwrite, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitImportGitSource {\n");
    
    sb.append("    overwrite: ").append(toIndentedString(overwrite)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

