/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class GitMergeOriginRef {
  @JsonProperty("cherryPickId")
  private Integer cherryPickId = null;

  @JsonProperty("pullRequestId")
  private Integer pullRequestId = null;

  @JsonProperty("revertId")
  private Integer revertId = null;

  public GitMergeOriginRef cherryPickId(Integer cherryPickId) {
    this.cherryPickId = cherryPickId;
    return this;
  }

   /**
   * Get cherryPickId
   * @return cherryPickId
  **/
  @ApiModelProperty(value = "")
  public Integer getCherryPickId() {
    return cherryPickId;
  }

  public void setCherryPickId(Integer cherryPickId) {
    this.cherryPickId = cherryPickId;
  }

  public GitMergeOriginRef pullRequestId(Integer pullRequestId) {
    this.pullRequestId = pullRequestId;
    return this;
  }

   /**
   * Get pullRequestId
   * @return pullRequestId
  **/
  @ApiModelProperty(value = "")
  public Integer getPullRequestId() {
    return pullRequestId;
  }

  public void setPullRequestId(Integer pullRequestId) {
    this.pullRequestId = pullRequestId;
  }

  public GitMergeOriginRef revertId(Integer revertId) {
    this.revertId = revertId;
    return this;
  }

   /**
   * Get revertId
   * @return revertId
  **/
  @ApiModelProperty(value = "")
  public Integer getRevertId() {
    return revertId;
  }

  public void setRevertId(Integer revertId) {
    this.revertId = revertId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitMergeOriginRef gitMergeOriginRef = (GitMergeOriginRef) o;
    return Objects.equals(this.cherryPickId, gitMergeOriginRef.cherryPickId) &&
        Objects.equals(this.pullRequestId, gitMergeOriginRef.pullRequestId) &&
        Objects.equals(this.revertId, gitMergeOriginRef.revertId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cherryPickId, pullRequestId, revertId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitMergeOriginRef {\n");
    
    sb.append("    cherryPickId: ").append(toIndentedString(cherryPickId)).append("\n");
    sb.append("    pullRequestId: ").append(toIndentedString(pullRequestId)).append("\n");
    sb.append("    revertId: ").append(toIndentedString(revertId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

