/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Collection of changes made in a pull request.
 */
@ApiModel(description = "Collection of changes made in a pull request.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class GitPullRequestIterationChanges {
  @JsonProperty("changeEntries")
  private List<GitPullRequestChange> changeEntries = null;

  @JsonProperty("nextSkip")
  private Integer nextSkip = null;

  @JsonProperty("nextTop")
  private Integer nextTop = null;

  public GitPullRequestIterationChanges changeEntries(List<GitPullRequestChange> changeEntries) {
    this.changeEntries = changeEntries;
    return this;
  }

  public GitPullRequestIterationChanges addChangeEntriesItem(GitPullRequestChange changeEntriesItem) {
    if (this.changeEntries == null) {
      this.changeEntries = new ArrayList<GitPullRequestChange>();
    }
    this.changeEntries.add(changeEntriesItem);
    return this;
  }

  /**
   * Changes made in the iteration.
   *
   * @return changeEntries
   **/
  @ApiModelProperty(value = "Changes made in the iteration.")
  public List<GitPullRequestChange> getChangeEntries() {
    return changeEntries;
  }

  public void setChangeEntries(List<GitPullRequestChange> changeEntries) {
    this.changeEntries = changeEntries;
  }

  public GitPullRequestIterationChanges nextSkip(Integer nextSkip) {
    this.nextSkip = nextSkip;
    return this;
  }

  /**
   * Value to specify as skip to get the next page of changes.  This will be zero if there are no more changes.
   *
   * @return nextSkip
   **/
  @ApiModelProperty(value = "Value to specify as skip to get the next page of changes.  This will be zero if there are no more changes.")
  public Integer getNextSkip() {
    return nextSkip;
  }

  public void setNextSkip(Integer nextSkip) {
    this.nextSkip = nextSkip;
  }

  public GitPullRequestIterationChanges nextTop(Integer nextTop) {
    this.nextTop = nextTop;
    return this;
  }

  /**
   * Value to specify as top to get the next page of changes.  This will be zero if there are no more changes.
   *
   * @return nextTop
   **/
  @ApiModelProperty(value = "Value to specify as top to get the next page of changes.  This will be zero if there are no more changes.")
  public Integer getNextTop() {
    return nextTop;
  }

  public void setNextTop(Integer nextTop) {
    this.nextTop = nextTop;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitPullRequestIterationChanges gitPullRequestIterationChanges = (GitPullRequestIterationChanges) o;
    return Objects.equals(this.changeEntries, gitPullRequestIterationChanges.changeEntries) &&
            Objects.equals(this.nextSkip, gitPullRequestIterationChanges.nextSkip) &&
            Objects.equals(this.nextTop, gitPullRequestIterationChanges.nextTop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeEntries, nextSkip, nextTop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitPullRequestIterationChanges {\n");

    sb.append("    changeEntries: ").append(toIndentedString(changeEntries)).append("\n");
    sb.append("    nextSkip: ").append(toIndentedString(nextSkip)).append("\n");
    sb.append("    nextTop: ").append(toIndentedString(nextTop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

