/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class GitTreeDiffResponse {
  @JsonProperty("continuationToken")
  private List<String> continuationToken = null;

  @JsonProperty("treeDiff")
  private GitTreeDiff treeDiff = null;

  public GitTreeDiffResponse continuationToken(List<String> continuationToken) {
    this.continuationToken = continuationToken;
    return this;
  }

  public GitTreeDiffResponse addContinuationTokenItem(String continuationTokenItem) {
    if (this.continuationToken == null) {
      this.continuationToken = new ArrayList<String>();
    }
    this.continuationToken.add(continuationTokenItem);
    return this;
  }

  /**
   * The HTTP client methods find the continuation token header in the response and populate this field.
   *
   * @return continuationToken
   **/
  @ApiModelProperty(value = "The HTTP client methods find the continuation token header in the response and populate this field.")
  public List<String> getContinuationToken() {
    return continuationToken;
  }

  public void setContinuationToken(List<String> continuationToken) {
    this.continuationToken = continuationToken;
  }

  public GitTreeDiffResponse treeDiff(GitTreeDiff treeDiff) {
    this.treeDiff = treeDiff;
    return this;
  }

  /**
   * Get treeDiff
   *
   * @return treeDiff
   **/
  @ApiModelProperty(value = "")
  public GitTreeDiff getTreeDiff() {
    return treeDiff;
  }

  public void setTreeDiff(GitTreeDiff treeDiff) {
    this.treeDiff = treeDiff;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitTreeDiffResponse gitTreeDiffResponse = (GitTreeDiffResponse) o;
    return Objects.equals(this.continuationToken, gitTreeDiffResponse.continuationToken) &&
            Objects.equals(this.treeDiff, gitTreeDiffResponse.treeDiff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(continuationToken, treeDiff);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitTreeDiffResponse {\n");

    sb.append("    continuationToken: ").append(toIndentedString(continuationToken)).append("\n");
    sb.append("    treeDiff: ").append(toIndentedString(treeDiff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

