/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class ImportRepositoryValidation {
  @JsonProperty("gitSource")
  private GitImportGitSource gitSource = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("tfvcSource")
  private GitImportTfvcSource tfvcSource = null;

  @JsonProperty("username")
  private String username = null;

  public ImportRepositoryValidation gitSource(GitImportGitSource gitSource) {
    this.gitSource = gitSource;
    return this;
  }

  /**
   * Get gitSource
   *
   * @return gitSource
   **/
  @ApiModelProperty(value = "")
  public GitImportGitSource getGitSource() {
    return gitSource;
  }

  public void setGitSource(GitImportGitSource gitSource) {
    this.gitSource = gitSource;
  }

  public ImportRepositoryValidation password(String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   *
   * @return password
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public ImportRepositoryValidation tfvcSource(GitImportTfvcSource tfvcSource) {
    this.tfvcSource = tfvcSource;
    return this;
  }

  /**
   * Get tfvcSource
   *
   * @return tfvcSource
   **/
  @ApiModelProperty(value = "")
  public GitImportTfvcSource getTfvcSource() {
    return tfvcSource;
  }

  public void setTfvcSource(GitImportTfvcSource tfvcSource) {
    this.tfvcSource = tfvcSource;
  }

  public ImportRepositoryValidation username(String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   *
   * @return username
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportRepositoryValidation importRepositoryValidation = (ImportRepositoryValidation) o;
    return Objects.equals(this.gitSource, importRepositoryValidation.gitSource) &&
            Objects.equals(this.password, importRepositoryValidation.password) &&
            Objects.equals(this.tfvcSource, importRepositoryValidation.tfvcSource) &&
            Objects.equals(this.username, importRepositoryValidation.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gitSource, password, tfvcSource, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportRepositoryValidation {\n");

    sb.append("    gitSource: ").append(toIndentedString(gitSource)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    tfvcSource: ").append(toIndentedString(tfvcSource)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

