/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class ItemModel {
  @JsonProperty("_links")
  private ReferenceLinks links = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("contentMetadata")
  private FileContentMetadata contentMetadata = null;

  @JsonProperty("isFolder")
  private Boolean isFolder = null;

  @JsonProperty("isSymLink")
  private Boolean isSymLink = null;

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("url")
  private String url = null;

  public ItemModel links(ReferenceLinks links) {
    this.links = links;
    return this;
  }

  /**
   * Get links
   *
   * @return links
   **/
  @ApiModelProperty(value = "")
  public ReferenceLinks getLinks() {
    return links;
  }

  public void setLinks(ReferenceLinks links) {
    this.links = links;
  }

  public ItemModel content(String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   *
   * @return content
   **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ItemModel contentMetadata(FileContentMetadata contentMetadata) {
    this.contentMetadata = contentMetadata;
    return this;
  }

  /**
   * Get contentMetadata
   *
   * @return contentMetadata
   **/
  @ApiModelProperty(value = "")
  public FileContentMetadata getContentMetadata() {
    return contentMetadata;
  }

  public void setContentMetadata(FileContentMetadata contentMetadata) {
    this.contentMetadata = contentMetadata;
  }

  public ItemModel isFolder(Boolean isFolder) {
    this.isFolder = isFolder;
    return this;
  }

  /**
   * Get isFolder
   *
   * @return isFolder
   **/
  @ApiModelProperty(value = "")
  public Boolean isIsFolder() {
    return isFolder;
  }

  public void setIsFolder(Boolean isFolder) {
    this.isFolder = isFolder;
  }

  public ItemModel isSymLink(Boolean isSymLink) {
    this.isSymLink = isSymLink;
    return this;
  }

  /**
   * Get isSymLink
   *
   * @return isSymLink
   **/
  @ApiModelProperty(value = "")
  public Boolean isIsSymLink() {
    return isSymLink;
  }

  public void setIsSymLink(Boolean isSymLink) {
    this.isSymLink = isSymLink;
  }

  public ItemModel path(String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   *
   * @return path
   **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public ItemModel url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemModel itemModel = (ItemModel) o;
    return Objects.equals(this.links, itemModel.links) &&
            Objects.equals(this.content, itemModel.content) &&
            Objects.equals(this.contentMetadata, itemModel.contentMetadata) &&
            Objects.equals(this.isFolder, itemModel.isFolder) &&
            Objects.equals(this.isSymLink, itemModel.isSymLink) &&
            Objects.equals(this.path, itemModel.path) &&
            Objects.equals(this.url, itemModel.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, content, contentMetadata, isFolder, isSymLink, path, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemModel {\n");

    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentMetadata: ").append(toIndentedString(contentMetadata)).append("\n");
    sb.append("    isFolder: ").append(toIndentedString(isFolder)).append("\n");
    sb.append("    isSymLink: ").append(toIndentedString(isSymLink)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

