/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class SourceToTargetRef {
    @JsonProperty("sourceRef")
    private String sourceRef = null;

    @JsonProperty("targetRef")
    private String targetRef = null;

    public SourceToTargetRef sourceRef(String sourceRef) {
        this.sourceRef = sourceRef;
        return this;
    }

    /**
     * The source ref to copy. For example, refs/heads/master.
     *
     * @return sourceRef
     **/
    @ApiModelProperty(value = "The source ref to copy. For example, refs/heads/master.")
    public String getSourceRef() {
        return sourceRef;
    }

    public void setSourceRef(String sourceRef) {
        this.sourceRef = sourceRef;
    }

    public SourceToTargetRef targetRef(String targetRef) {
        this.targetRef = targetRef;
        return this;
    }

    /**
     * The target ref to update. For example, refs/heads/master.
     *
     * @return targetRef
     **/
    @ApiModelProperty(value = "The target ref to update. For example, refs/heads/master.")
    public String getTargetRef() {
        return targetRef;
    }

    public void setTargetRef(String targetRef) {
        this.targetRef = targetRef;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceToTargetRef sourceToTargetRef = (SourceToTargetRef) o;
        return Objects.equals(this.sourceRef, sourceToTargetRef.sourceRef) &&
                Objects.equals(this.targetRef, sourceToTargetRef.targetRef);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sourceRef, targetRef);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SourceToTargetRef {\n");

        sb.append("    sourceRef: ").append(toIndentedString(sourceRef)).append("\n");
        sb.append("    targetRef: ").append(toIndentedString(targetRef)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

