/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;
import therealflamingo.ado.models.IdentityRef;
import therealflamingo.ado.models.ReferenceLinks;
import therealflamingo.ado.models.TfvcShallowBranchRef;

/**
 * Metadata for a branchref.
 */
@ApiModel(description = "Metadata for a branchref.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class TfvcBranchRef extends TfvcShallowBranchRef {
  @JsonProperty("path")
  private String path = null;

  @JsonProperty("_links")
  private ReferenceLinks links = null;

  @JsonProperty("createdDate")
  private OffsetDateTime createdDate = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("isDeleted")
  private Boolean isDeleted = null;

  @JsonProperty("owner")
  private IdentityRef owner = null;

  @JsonProperty("url")
  private String url = null;

  public TfvcBranchRef path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path for the branch.
   * @return path
  **/
  @ApiModelProperty(value = "Path for the branch.")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public TfvcBranchRef links(ReferenceLinks links) {
    this.links = links;
    return this;
  }

   /**
   * A collection of REST reference links.
   * @return links
  **/
  @ApiModelProperty(value = "A collection of REST reference links.")
  public ReferenceLinks getLinks() {
    return links;
  }

  public void setLinks(ReferenceLinks links) {
    this.links = links;
  }

  public TfvcBranchRef createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Creation date of the branch.
   * @return createdDate
  **/
  @ApiModelProperty(value = "Creation date of the branch.")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

  public TfvcBranchRef description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Branch description.
   * @return description
  **/
  @ApiModelProperty(value = "Branch description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TfvcBranchRef isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Is the branch deleted?
   * @return isDeleted
  **/
  @ApiModelProperty(value = "Is the branch deleted?")
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public TfvcBranchRef owner(IdentityRef owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Alias or display name of user
   * @return owner
  **/
  @ApiModelProperty(value = "Alias or display name of user")
  public IdentityRef getOwner() {
    return owner;
  }

  public void setOwner(IdentityRef owner) {
    this.owner = owner;
  }

  public TfvcBranchRef url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL to retrieve the item.
   * @return url
  **/
  @ApiModelProperty(value = "URL to retrieve the item.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TfvcBranchRef tfvcBranchRef = (TfvcBranchRef) o;
    return Objects.equals(this.path, tfvcBranchRef.path) &&
        Objects.equals(this.links, tfvcBranchRef.links) &&
        Objects.equals(this.createdDate, tfvcBranchRef.createdDate) &&
        Objects.equals(this.description, tfvcBranchRef.description) &&
        Objects.equals(this.isDeleted, tfvcBranchRef.isDeleted) &&
        Objects.equals(this.owner, tfvcBranchRef.owner) &&
        Objects.equals(this.url, tfvcBranchRef.url) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, links, createdDate, description, isDeleted, owner, url, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TfvcBranchRef {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

