/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class TfvcMergeSource {
  @JsonProperty("isRename")
  private Boolean isRename = null;

  @JsonProperty("serverItem")
  private String serverItem = null;

  @JsonProperty("versionFrom")
  private Integer versionFrom = null;

  @JsonProperty("versionTo")
  private Integer versionTo = null;

  public TfvcMergeSource isRename(Boolean isRename) {
    this.isRename = isRename;
    return this;
  }

   /**
   * Indicates if this a rename source. If false, it is a merge source.
   * @return isRename
  **/
  @ApiModelProperty(value = "Indicates if this a rename source. If false, it is a merge source.")
  public Boolean isIsRename() {
    return isRename;
  }

  public void setIsRename(Boolean isRename) {
    this.isRename = isRename;
  }

  public TfvcMergeSource serverItem(String serverItem) {
    this.serverItem = serverItem;
    return this;
  }

   /**
   * The server item of the merge source.
   * @return serverItem
  **/
  @ApiModelProperty(value = "The server item of the merge source.")
  public String getServerItem() {
    return serverItem;
  }

  public void setServerItem(String serverItem) {
    this.serverItem = serverItem;
  }

  public TfvcMergeSource versionFrom(Integer versionFrom) {
    this.versionFrom = versionFrom;
    return this;
  }

   /**
   * Start of the version range.
   * @return versionFrom
  **/
  @ApiModelProperty(value = "Start of the version range.")
  public Integer getVersionFrom() {
    return versionFrom;
  }

  public void setVersionFrom(Integer versionFrom) {
    this.versionFrom = versionFrom;
  }

  public TfvcMergeSource versionTo(Integer versionTo) {
    this.versionTo = versionTo;
    return this;
  }

   /**
   * End of the version range.
   * @return versionTo
  **/
  @ApiModelProperty(value = "End of the version range.")
  public Integer getVersionTo() {
    return versionTo;
  }

  public void setVersionTo(Integer versionTo) {
    this.versionTo = versionTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TfvcMergeSource tfvcMergeSource = (TfvcMergeSource) o;
    return Objects.equals(this.isRename, tfvcMergeSource.isRename) &&
        Objects.equals(this.serverItem, tfvcMergeSource.serverItem) &&
        Objects.equals(this.versionFrom, tfvcMergeSource.versionFrom) &&
        Objects.equals(this.versionTo, tfvcMergeSource.versionTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isRename, serverItem, versionFrom, versionTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TfvcMergeSource {\n");
    
    sb.append("    isRename: ").append(toIndentedString(isRename)).append("\n");
    sb.append("    serverItem: ").append(toIndentedString(serverItem)).append("\n");
    sb.append("    versionFrom: ").append(toIndentedString(versionFrom)).append("\n");
    sb.append("    versionTo: ").append(toIndentedString(versionTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

