/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Metadata for a shelveset.
 */
@ApiModel(description = "Metadata for a shelveset.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class TfvcShelveset extends TfvcShelvesetRef {
  @JsonProperty("_links")
  private ReferenceLinks links = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("commentTruncated")
  private Boolean commentTruncated = null;

  @JsonProperty("createdDate")
  private OffsetDateTime createdDate = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("owner")
  private IdentityRef owner = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("changes")
  private List<TfvcChange> changes = null;

  @JsonProperty("notes")
  private List<CheckinNote> notes = null;

  @JsonProperty("policyOverride")
  private TfvcPolicyOverrideInfo policyOverride = null;

  @JsonProperty("workItems")
  private List<AssociatedWorkItem> workItems = null;

  public TfvcShelveset links(ReferenceLinks links) {
    this.links = links;
    return this;
  }

  /**
   * List of reference links for the shelveset.
   *
   * @return links
   **/
  @ApiModelProperty(value = "List of reference links for the shelveset.")
  public ReferenceLinks getLinks() {
    return links;
  }

  public void setLinks(ReferenceLinks links) {
    this.links = links;
  }

  public TfvcShelveset comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Shelveset comment.
   *
   * @return comment
   **/
  @ApiModelProperty(value = "Shelveset comment.")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public TfvcShelveset commentTruncated(Boolean commentTruncated) {
    this.commentTruncated = commentTruncated;
    return this;
  }

  /**
   * Shelveset comment truncated as applicable.
   *
   * @return commentTruncated
   **/
  @ApiModelProperty(value = "Shelveset comment truncated as applicable.")
  public Boolean isCommentTruncated() {
    return commentTruncated;
  }

  public void setCommentTruncated(Boolean commentTruncated) {
    this.commentTruncated = commentTruncated;
  }

  public TfvcShelveset createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Shelveset create date.
   *
   * @return createdDate
   **/
  @ApiModelProperty(value = "Shelveset create date.")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

  public TfvcShelveset id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Shelveset Id.
   *
   * @return id
   **/
  @ApiModelProperty(value = "Shelveset Id.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TfvcShelveset name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Shelveset name.
   *
   * @return name
   **/
  @ApiModelProperty(value = "Shelveset name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TfvcShelveset owner(IdentityRef owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Shelveset Owner.
   *
   * @return owner
   **/
  @ApiModelProperty(value = "Shelveset Owner.")
  public IdentityRef getOwner() {
    return owner;
  }

  public void setOwner(IdentityRef owner) {
    this.owner = owner;
  }

  public TfvcShelveset url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Shelveset Url.
   *
   * @return url
   **/
  @ApiModelProperty(value = "Shelveset Url.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public TfvcShelveset changes(List<TfvcChange> changes) {
    this.changes = changes;
    return this;
  }

  public TfvcShelveset addChangesItem(TfvcChange changesItem) {
    if (this.changes == null) {
      this.changes = new ArrayList<TfvcChange>();
    }
    this.changes.add(changesItem);
    return this;
  }

  /**
   * List of changes.
   *
   * @return changes
   **/
  @ApiModelProperty(value = "List of changes.")
  public List<TfvcChange> getChanges() {
    return changes;
  }

  public void setChanges(List<TfvcChange> changes) {
    this.changes = changes;
  }

  public TfvcShelveset notes(List<CheckinNote> notes) {
    this.notes = notes;
    return this;
  }

  public TfvcShelveset addNotesItem(CheckinNote notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<CheckinNote>();
    }
    this.notes.add(notesItem);
    return this;
  }

  /**
   * List of checkin notes.
   *
   * @return notes
   **/
  @ApiModelProperty(value = "List of checkin notes.")
  public List<CheckinNote> getNotes() {
    return notes;
  }

  public void setNotes(List<CheckinNote> notes) {
    this.notes = notes;
  }

  public TfvcShelveset policyOverride(TfvcPolicyOverrideInfo policyOverride) {
    this.policyOverride = policyOverride;
    return this;
  }

  /**
   * Policy override information if applicable.
   *
   * @return policyOverride
   **/
  @ApiModelProperty(value = "Policy override information if applicable.")
  public TfvcPolicyOverrideInfo getPolicyOverride() {
    return policyOverride;
  }

  public void setPolicyOverride(TfvcPolicyOverrideInfo policyOverride) {
    this.policyOverride = policyOverride;
  }

  public TfvcShelveset workItems(List<AssociatedWorkItem> workItems) {
    this.workItems = workItems;
    return this;
  }

  public TfvcShelveset addWorkItemsItem(AssociatedWorkItem workItemsItem) {
    if (this.workItems == null) {
      this.workItems = new ArrayList<AssociatedWorkItem>();
    }
    this.workItems.add(workItemsItem);
    return this;
  }

  /**
   * List of associated workitems.
   *
   * @return workItems
   **/
  @ApiModelProperty(value = "List of associated workitems.")
  public List<AssociatedWorkItem> getWorkItems() {
    return workItems;
  }

  public void setWorkItems(List<AssociatedWorkItem> workItems) {
    this.workItems = workItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TfvcShelveset tfvcShelveset = (TfvcShelveset) o;
    return Objects.equals(this.links, tfvcShelveset.links) &&
            Objects.equals(this.comment, tfvcShelveset.comment) &&
            Objects.equals(this.commentTruncated, tfvcShelveset.commentTruncated) &&
            Objects.equals(this.createdDate, tfvcShelveset.createdDate) &&
            Objects.equals(this.id, tfvcShelveset.id) &&
            Objects.equals(this.name, tfvcShelveset.name) &&
            Objects.equals(this.owner, tfvcShelveset.owner) &&
            Objects.equals(this.url, tfvcShelveset.url) &&
            Objects.equals(this.changes, tfvcShelveset.changes) &&
            Objects.equals(this.notes, tfvcShelveset.notes) &&
            Objects.equals(this.policyOverride, tfvcShelveset.policyOverride) &&
            Objects.equals(this.workItems, tfvcShelveset.workItems) &&
            super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, comment, commentTruncated, createdDate, id, name, owner, url, changes, notes, policyOverride, workItems, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TfvcShelveset {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    commentTruncated: ").append(toIndentedString(commentTruncated)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    policyOverride: ").append(toIndentedString(policyOverride)).append("\n");
    sb.append("    workItems: ").append(toIndentedString(workItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

