/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import therealflamingo.ado.models.GitRefUpdate;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-28T21:17:42.501+02:00")
public class UpdateRefsRequest {
  @JsonProperty("refUpdateRequests")
  private List<GitRefUpdate> refUpdateRequests = null;

  /**
   * Gets or Sets updateMode
   */
  public enum UpdateModeEnum {
    BESTEFFORT("bestEffort"),
    
    ALLORNONE("allOrNone");

    private String value;

    UpdateModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UpdateModeEnum fromValue(String value) {
      for (UpdateModeEnum b : UpdateModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("updateMode")
  private UpdateModeEnum updateMode = null;

  public UpdateRefsRequest refUpdateRequests(List<GitRefUpdate> refUpdateRequests) {
    this.refUpdateRequests = refUpdateRequests;
    return this;
  }

  public UpdateRefsRequest addRefUpdateRequestsItem(GitRefUpdate refUpdateRequestsItem) {
    if (this.refUpdateRequests == null) {
      this.refUpdateRequests = new ArrayList<GitRefUpdate>();
    }
    this.refUpdateRequests.add(refUpdateRequestsItem);
    return this;
  }

   /**
   * Get refUpdateRequests
   * @return refUpdateRequests
  **/
  @ApiModelProperty(value = "")
  public List<GitRefUpdate> getRefUpdateRequests() {
    return refUpdateRequests;
  }

  public void setRefUpdateRequests(List<GitRefUpdate> refUpdateRequests) {
    this.refUpdateRequests = refUpdateRequests;
  }

  public UpdateRefsRequest updateMode(UpdateModeEnum updateMode) {
    this.updateMode = updateMode;
    return this;
  }

   /**
   * Get updateMode
   * @return updateMode
  **/
  @ApiModelProperty(value = "")
  public UpdateModeEnum getUpdateMode() {
    return updateMode;
  }

  public void setUpdateMode(UpdateModeEnum updateMode) {
    this.updateMode = updateMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateRefsRequest updateRefsRequest = (UpdateRefsRequest) o;
    return Objects.equals(this.refUpdateRequests, updateRefsRequest.refUpdateRequests) &&
        Objects.equals(this.updateMode, updateRefsRequest.updateMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refUpdateRequests, updateMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateRefsRequest {\n");
    
    sb.append("    refUpdateRequests: ").append(toIndentedString(refUpdateRequests)).append("\n");
    sb.append("    updateMode: ").append(toIndentedString(updateMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

