/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.api;

import org.junit.Ignore;
import org.junit.Test;
import therealflamingo.ado.models.GitCommitRef;

import java.util.List;
import java.util.UUID;

/**
 * API tests for MergeBasesApi
 */
@Ignore
public class MergeBasesApiTest {

    private final MergeBasesApi api = new MergeBasesApi();


    /**
     * Find the merge bases of two commits, optionally across forks. If otherRepositoryId is not specified, the merge bases will only be calculated within the context of the local repositoryNameOrId.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void mergeBasesListTest() throws Exception {
        String organization = null;
        String repositoryNameOrId = null;
        String commitId = null;
        String otherCommitId = null;
        String project = null;
        String apiVersion = null;
        UUID otherCollectionId = null;
        UUID otherRepositoryId = null;
        List<GitCommitRef> response = api.mergeBasesList(organization, repositoryNameOrId, commitId, otherCommitId, project, apiVersion, otherCollectionId, otherRepositoryId);

        // TODO: test validations
    }

}
