/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.api;

import org.junit.Ignore;
import org.junit.Test;
import therealflamingo.ado.models.WebApiCreateTagRequestData;
import therealflamingo.ado.models.WebApiTagDefinition;

import java.util.List;

/**
 * API tests for PullRequestLabelsApi
 */
@Ignore
public class PullRequestLabelsApiTest {

    private final PullRequestLabelsApi api = new PullRequestLabelsApi();


    /**
     * Create a tag (if that does not exists yet) and add that as a label (tag) for a specified pull request. The only required field is the name of the new label (tag).
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void pullRequestLabelsCreateTest() throws Exception {
        String organization = null;
        WebApiCreateTagRequestData body = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        String projectId = null;
        WebApiTagDefinition response = api.pullRequestLabelsCreate(organization, body, repositoryId, pullRequestId, project, apiVersion, projectId);

        // TODO: test validations
    }

    /**
     * Removes a label (tag) from the set of those assigned to the pull request. The tag itself will not be deleted.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void pullRequestLabelsDeleteTest() throws Exception {
        String organization = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String labelIdOrName = null;
        String project = null;
        String apiVersion = null;
        String projectId = null;
        api.pullRequestLabelsDelete(organization, repositoryId, pullRequestId, labelIdOrName, project, apiVersion, projectId);

        // TODO: test validations
    }

    /**
     * Retrieves a single label (tag) that has been assigned to a pull request.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void pullRequestLabelsGetTest() throws Exception {
        String organization = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String labelIdOrName = null;
        String project = null;
        String apiVersion = null;
        String projectId = null;
        WebApiTagDefinition response = api.pullRequestLabelsGet(organization, repositoryId, pullRequestId, labelIdOrName, project, apiVersion, projectId);

        // TODO: test validations
    }

    /**
     * Get all the labels (tags) assigned to a pull request.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void pullRequestLabelsListTest() throws Exception {
        String organization = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        String projectId = null;
        List<WebApiTagDefinition> response = api.pullRequestLabelsList(organization, repositoryId, pullRequestId, project, apiVersion, projectId);

        // TODO: test validations
    }

}
