/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.api;

import therealflamingo.ado.models.Attachment;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PullRequestAttachmentsApi
 */
@Ignore
public class PullRequestAttachmentsApiTest {

    private final PullRequestAttachmentsApi api = new PullRequestAttachmentsApi();

    
    /**
     * 
     *
     * Attach a new file to a pull request.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestAttachmentsCreateTest() throws Exception {
        String organization = null;
        String body = null;
        String fileName = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        Attachment response = api.pullRequestAttachmentsCreate(organization, body, fileName, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete a pull request attachment.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestAttachmentsDeleteTest() throws Exception {
        String organization = null;
        String fileName = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        api.pullRequestAttachmentsDelete(organization, fileName, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get the file content of a pull request attachment.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestAttachmentsGetTest() throws Exception {
        String organization = null;
        String fileName = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        String response = api.pullRequestAttachmentsGet(organization, fileName, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get a list of files attached to a given pull request.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestAttachmentsListTest() throws Exception {
        String organization = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        List<Attachment> response = api.pullRequestAttachmentsList(organization, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
}
