/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.api;

import therealflamingo.ado.models.JsonPatchDocument;
import therealflamingo.ado.models.PropertiesCollection;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PullRequestPropertiesApi
 */
@Ignore
public class PullRequestPropertiesApiTest {

    private final PullRequestPropertiesApi api = new PullRequestPropertiesApi();

    
    /**
     * 
     *
     * Get external properties of the pull request.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestPropertiesListTest() throws Exception {
        String organization = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        PropertiesCollection response = api.pullRequestPropertiesList(organization, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Create or update pull request external properties. The patch operation can be &#x60;add&#x60;, &#x60;replace&#x60; or &#x60;remove&#x60;. For &#x60;add&#x60; operation, the path can be empty. If the path is empty, the value must be a list of key value pairs. For &#x60;replace&#x60; operation, the path cannot be empty. If the path does not exist, the property will be added to the collection. For &#x60;remove&#x60; operation, the path cannot be empty. If the path does not exist, no action will be performed.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pullRequestPropertiesUpdateTest() throws Exception {
        String organization = null;
        JsonPatchDocument body = null;
        String repositoryId = null;
        Integer pullRequestId = null;
        String project = null;
        String apiVersion = null;
        PropertiesCollection response = api.pullRequestPropertiesUpdate(organization, body, repositoryId, pullRequestId, project, apiVersion);

        // TODO: test validations
    }
    
}
