/*
 * Git
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.2-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package therealflamingo.ado.api;

import org.junit.Ignore;
import org.junit.Test;
import therealflamingo.ado.models.GitAsyncRefOperationParameters;
import therealflamingo.ado.models.GitRevert;

/**
 * API tests for RevertsApi
 */
@Ignore
public class RevertsApiTest {

    private final RevertsApi api = new RevertsApi();


    /**
     * Starts the operation to create a new branch which reverts changes introduced by either a specific commit or commits that are associated to a pull request.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void revertsCreateTest() throws Exception {
        String organization = null;
        GitAsyncRefOperationParameters body = null;
        String project = null;
        String repositoryId = null;
        String apiVersion = null;
        GitRevert response = api.revertsCreate(organization, body, project, repositoryId, apiVersion);

        // TODO: test validations
    }

    /**
     * Retrieve information about a revert operation by revert Id.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void revertsGetRevertTest() throws Exception {
        String organization = null;
        String project = null;
        Integer revertId = null;
        String repositoryId = null;
        String apiVersion = null;
        GitRevert response = api.revertsGetRevert(organization, project, revertId, repositoryId, apiVersion);

        // TODO: test validations
    }

    /**
     * Retrieve information about a revert operation for a specific branch.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void revertsGetRevertForRefNameTest() throws Exception {
        String organization = null;
        String project = null;
        String repositoryId = null;
        String refName = null;
        String apiVersion = null;
        GitRevert response = api.revertsGetRevertForRefName(organization, project, repositoryId, refName, apiVersion);

        // TODO: test validations
    }

}
